### ISSUE TITLE
error using example

### ISSUE THREAD

**Issue by hwaynefair** [vorg/get-image-urls#2]
"file" argument must be a non-empty string

code: (on Run-kit_nmp)
var getImageUrls = require("get-image-urls")
getImageUrls('https://www.ftd.com/33952/time-to-celebrate-rainbow-rose-bouquet-prd/FFBR/?cvosrc=PLA.Google.FFBR&gbb=FK317', function(err, images) {
  if (!err) {
    console.log('Images found', images.length);
    console.log(images);
  }
  else {
    console.log('ERROR', err);
  }
})

**Comment by vorg** [comment]
Hi,

I believe you can't run it on runkit as it needs Phantom js installed on the system.

Similar to : https://github.com/vorg/get-image-urls/issues/1

**Comment by hwaynefair** [comment]
Thanks, Marcin!
